version: '3'

services:
    allgold-api:
        container_name: allgold-api
        build: ./build
        ports:
            - 8888:80
        volumes:
            - ./api:/var/www/html
        depends_on: 
            - allgold-db

    allgold-db:
        container_name: allgold-db
        image: mariadb:latest
        ports:
            - 3306:3306
        volumes:
            - ./mariadb:/var/lib/mysql
            - ./sql:/opt/scripts
        environment:
            TZ: "Europe/Berlin"
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_USER: 'test'
            MYSQL_PASSWORD: 'test'
            MYSQL_DATABASE: 'allgold'
